# Generated by Django 5.2.1 on 2025-05-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiazki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ksiazka',
            options={'verbose_name': 'Książka', 'verbose_name_plural': 'Książki'},
        ),
        migrations.AlterModelOptions(
            name='wypozyczenie',
            options={'verbose_name': 'Wypozyczenie', 'verbose_name_plural': 'Wypożyczenia'},
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='okladki/'),
        ),
    ]
