# Generated by Django 5.2.1 on 2025-05-18 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiazki', '0002_alter_ksiazka_options_alter_wypozyczenie_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StronaKsiazki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_strony', models.PositiveIntegerField()),
                ('tresc', models.TextField()),
                ('ksiazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strony', to='ksiazki.ksiazka')),
            ],
            options={
                'verbose_name': 'Strona książki',
                'verbose_name_plural': 'Strony książki',
                'ordering': ['numer_strony'],
            },
        ),
    ]
