# Generated by Django 5.2.1 on 2025-05-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksiazki', '0003_stronaksiazki'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksiazka',
            name='tresc',
            field=models.TextField(blank=True, help_text='Wpisz treść książki tutaj', null=True),
        ),
    ]
